### PR TITLE
Update buildtest.yml

### PR DESCRIPTION
**Pull request by sjunges**
Support latest, which is currently ubuntu 24.04

### CODE REVIEW

**Comment by volkm** [comment]
Looks good to me

Am 17. Mai 2024 22:04:55 MESZ schrieb Sebastian Junges ***@***.***>:

**Comment by sjunges** [comment]
I am now confused, because latest is used further below for the test & deploy. Should it then also be used up here?

**Comment by volkm** [comment]
The tests are split into two categories:
- Build, Test and Deploy runs on `latest` and also deploys the Docker images for the latest base image
- Build and Test runs on a specific Ubuntu/Debian version

I suggest to simply add `ubuntu-24.04` to the list of images.

**Comment by sjunges** [comment]
LGTM! Should we merge this after the basesystem?

**Comment by volkm** [comment]
Tests run through with the updated basesystem now.

**Pull request merged**
